version: '3.7'
services:
  
  
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - ./data/postgres:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'
    networks:
      red:  

  
    
      
networks:
  red: